module.exports.resorts = [
    'Big Squaw',
    'Baker Mountain',
    'Ski Ward',
    'Pats Peak',
    'Storrs Hill',
    'Hidden Valley',
    'Titus Mountain',
    'Appalachian Ski Mountain',
    'Stevens Pass',
    'Mount Bachelor',
    'Mount Hood Meadows',
    'Timberline Lodge',
    'Diamond Peak',
    'Jackson Hole',
    'Big Sky',
    'Sun Valley',
    'Winter Park',
    'Breckenridge'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]

